version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: disaster_postgres
    restart: always
    ports:
      - '5332:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: disaster_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
